{{- if .Values.api.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pogues.api.fullname" . }}
  labels:
    {{- include "pogues.api.labels" . | nindent 4 }}
spec:
  {{- if not .Values.api.autoscaling.enabled }}
  replicas: {{ .Values.api.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "pogues.api.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.api.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "pogues.api.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.api.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "pogues.api.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.api.podSecurityContext | nindent 8 }}
      {{- if .Values.postgresql.enabled }}
      initContainers:
        - name: check-db-ready
          image: postgres:11.6
          command: ['sh', '-c', 
            until pg_isready -h {{ include "pogues.postgresql.fullname" . }} -p {{ .Values.postgresql.auth.port}}; 
            do echo waiting for database; sleep 2; done;]
       {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.api.securityContext | nindent 12 }}
          image: "{{ .Values.api.image.repository }}:{{ .Values.api.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.api.image.pullPolicy }}
          env:
          {{- if .Values.postgresql.enabled }}
          - name: FR_INSEE_POGUES_PERSISTENCE_DATABASE_HOST
            value:  {{ .Values.postgresql.fullnameOverride | quote}}
          - name: FR_INSEE_POGUES_PERSISTENCE_DATABASE_PORT
            value: 5432
          - name: FR_INSEE_POGUES_PERSISTENCE_DATABASE_SCHEMA
            value: {{ .Values.postgresql.auth.database | quote}}
          - name: FR_INSEE_POGUES_PERSISTENCE_DATABASE_USER
            value: {{ .Values.postgresql.auth.username | quote}}
          - name: FR_INSEE_POGUES_PERSISTENCE_DATABASE_PASSWORD
            value: {{ .Values.postgresql.auth.password | quote}}
          - name: FR_INSEE_POGUES_PERSISTENCE_DATABASE_TABLE
            value: pogues
          {{- end }}
          envFrom:
            - configMapRef:
                name: {{ template "pogues.api.fullname" . }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources:
            {{- toYaml .Values.api.resources | nindent 12 }}
      {{- with .Values.api.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.api.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.api.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end -}}