{{- if .Values.ui.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "orbeon-existdb.ui.fullname" . }}-configmap
  labels:
    app: {{ template "orbeon-existdb.ui.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
{{- if .Values.ui.env }}
{{- range $key, $value := .Values.ui.env }}
  {{ $key }}: {{ include "render-value" ( dict "value" $value "context" $) | quote }}
{{- end -}}
{{- end -}}
{{- end -}}