{{- if .Values.ui.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "orbeon-existdb.ui.fullname" . }}
  labels:
    {{- include "orbeon-existdb.ui.labels" . | nindent 4 }}
spec:
  {{- if not .Values.ui.autoscaling.enabled }}
  replicas: {{ .Values.ui.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "orbeon-existdb.ui.selectorLabels" . | nindent 6 }}
  {{- with  .Values.ui.deploymentStrategy }}
  strategy: 
    {{- toYaml . | nindent 4 }}
  {{- end }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/ui/configmap.yaml") . | sha256sum }}
      {{- with .Values.ui.podAnnotations }}
      {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "orbeon-existdb.ui.selectorLabels" . | nindent 8 }}
        {{- with .Values.ui.podAnnotationsLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.ui.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.ui.podSecurityContext }} # S'il y a des values, ça écrit "securityContext:" et la suite, sinon ça ne met rien 
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.ui.securityContext | nindent 12 }}
          image: "{{ .Values.ui.image.repository }}:{{ .Values.ui.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.ui.image.pullPolicy }}
          {{- if and .Values.ui.enabled .Values.ui.env }}
          envFrom:
            - configMapRef:
                name: {{ template "orbeon-existdb.ui.fullname" . }}
          {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.ui.container.port }}
              protocol: TCP
          {{- with .Values.ui.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.ui.resources | nindent 12 }}
      {{- with .Values.ui.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}      
      {{- with .Values.ui.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.ui.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.ui.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}