{{- if .Values.ui.networkPolicy.enabled -}}
---
uiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Values.ui.networkPolicy.config.name }}
spec:
  {{- with .Values.ui.networkPolicy.config.spec }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
{{- end -}}
