apiVersion: v2
name: queen
description: A Helm chart for Queen API, UI and DB

dependencies:
  - name: postgresql
    condition: postgresql.enabled
    version: 16.7.27
    repository: https://charts.bitnami.com/bitnami

type: application
version: 0.6.0
appVersion: "4.0.0"
