{{- if .Values.api.sealedSecret.enabled -}}
{{- range $key, $value := .Values.api.sealedSecret.config }}
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ $key }}
spec:
  encryptedData:
  {{- range $cle, $valeur := $value.secretEnv }}
    {{ $cle }}: {{ $valeur }}
  {{- end }}
  template:
    metadata:
      name: {{ $key }}
      namespace: {{ $value.namespace }}
    type: Opaque
{{- end }}
{{- end -}}