{{- if .Values.enojava.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "eno-ws.enojava.fullname" . }}-configmap
  labels:
    app: {{ template "eno-ws.enojava.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
{{- if .Values.enojava.env }}
{{- range $key, $value := .Values.enojava.env }}
  {{ $key }}: {{ include "render-value" ( dict "value" $value "context" $ ) | quote }}
{{- end -}}
{{- end -}}
{{- end -}}