{{- if .Values.enojava.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "eno-ws.enojava.fullname" . }}
  labels:
    {{- include "eno-ws.enojava.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.enojava.deploymentAnnotations | nindent 4 }}
spec:
  {{- if not .Values.enojava.autoscaling.enabled }}
  replicas: {{ .Values.enojava.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "eno-ws.enojava.selectorLabels" . | nindent 6 }}  
  {{- with  .Values.deploymentStrategy }}
  strategy: 
    {{- toYaml . | nindent 4 }}
  {{- end }}
  template:
    metadata:
      annotations:
        {{- if .Values.enojava.env }}
        checksum/config: {{ include (print $.Template.BasePath "/java/configmap.yaml") . | sha256sum }}
        {{- end }}
      {{- with .Values.enojava.podAnnotations }}
      {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "eno-ws.enojava.selectorLabels" . | nindent 8 }}
        {{- with .Values.enojava.podAnnotationsLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.enojava.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.enojava.podSecurityContext }} # S'il y a des values, ça écrit "securityContext:" et la suite, sinon ça ne met rien 
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.enojava.securityContext | nindent 12 }}
          image: "{{ .Values.enojava.image.repository }}:{{ .Values.enojava.image.tag }}"
          imagePullPolicy: {{ .Values.enojava.image.pullPolicy }}
          {{- if .Values.enojava.env }}
          envFrom:
            - configMapRef:
                name: {{ template "eno-ws.enojava.fullname" . }}-configmap
          {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.enojava.container.port }}
              protocol: TCP
          {{- with .Values.enojava.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.enojava.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.enojava.resources | nindent 12 }}
      {{- with .Values.enojava.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.enojava.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.enojava.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end -}}