{{- if and .Values.enojava.enabled .Values.enojava.ingress.enabled}}
{{- $fullName := include "eno-ws.enojava.fullname" . -}}
{{- $svcPort := .Values.enojava.service.port -}}
{{- if and .Values.enojava.ingress.className (not (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion)) }}
  {{- if not (hasKey .Values.enojava.ingress.annotations "kubernetes.io/ingress.class") }}
  {{- $_ := set .Values.enojava.ingress.annotations "kubernetes.io/ingress.class" .Values.enojava.ingress.className}}
  {{- end }}
{{- end }}
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "eno-ws.enojava.labels" . | nindent 4 }}
  {{- with .Values.enojava.ingress.annotations }}
  annotations:
    {{- include "render-value" (dict "value" . "context" $) | nindent 4 }}
  {{- end }}
spec:
  {{- if and .Values.enojava.ingress.className (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion) }}
  ingressClassName: {{ .Values.enojava.ingress.className }}
  {{- end }}
  {{- if .Values.enojava.ingress.tls }}
  tls:
    {{- range .Values.enojava.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ include "render-value" (dict "value" . "context" $) | quote }}
        {{- end }}
      secretName: {{ .secretName | default (printf "%s-cert" $fullName) }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.enojava.ingress.hosts }}
    - host: {{ include "render-value" (dict "value" .host "context" $) | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            {{- if and .pathType (semverCompare ">=1.18-0" $.Capabilities.KubeVersion.GitVersion) }}
            pathType: Prefix
            {{- end }}
            backend:
              {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
              service:
                name: {{ $fullName }}
                port:
                  number: {{ $svcPort }}
              {{- else }}
              serviceName: {{ $fullName }}
              servicePort: {{ $svcPort }}
              {{- end }}
          {{- end }}
    {{- end }}
{{- end }}