{{if and .Values.enojava.enabled .Values.enojava.serviceAccount.create}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "eno-ws.enojava.serviceAccountName" . }}
  labels:
    {{- include "eno-ws.enojava.labels" . | nindent 4 }}
  {{- with .Values.enojava.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
