{{- if .Values.api.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pearl.api.fullname" . }}
  labels:
    {{- include "pearl.api.labels" . | nindent 4 }}
spec:
  {{- if not .Values.api.autoscaling.enabled }}
  replicas: {{ .Values.api.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "pearl.api.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/api/configmap.yaml") . | sha256sum }}
      labels:
        {{- include "pearl.api.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.api.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "pearl.api.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.api.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.api.securityContext | nindent 12 }}
          image: "{{ .Values.api.image.repository }}:{{ .Values.api.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.api.image.pullPolicy }}

          {{- if or .Values.postgresql.enabled .Values.api.vaultStaticSecret.enabled }}
          env:
            {{- if .Values.postgresql.enabled }}
            - name: FR_INSEE_PEARLJAM_PERSISTENCE_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "pearl.postgresql.fullname" .}}
                  key: password
            - name: FR_INSEE_PEARLJAM_PERSISTENCE_DATABASE_HOST
              value:  {{ include "pearl.postgresql.fullname" . }}
            - name: FR_INSEE_PEARLJAM_PERSISTENCE_DATABASE_USER
              value: {{ .Values.postgresql.auth.username | quote}}
            - name: FR_INSEE_PEARLJAM_PERSISTENCE_DATABASE_SCHEMA
              value: {{ .Values.postgresql.auth.database | quote}}
            {{- end }}

            {{- if .Values.api.vaultStaticSecret.enabled }}
            {{- range $key, $value := .Values.api.vaultStaticSecret.config }}
            - name:  {{ $value.nomEnv }}
              valueFrom:
                secretKeyRef: 
                  name: {{ $value.secretName }}
                  key:  {{ $value.keyUsed }}
            {{- end }}
            {{- end }}
          {{- end }}

          {{- if or .Values.api.env .Values.api.sealedSecret.enabled }}
          envFrom:
            {{- if .Values.api.env }}
            - configMapRef:
                name: {{ template "pearl.api.fullname" . }}
            {{- end }}
            {{- if .Values.api.sealedSecret.enabled }}            
            {{- range $key, $value := .Values.api.sealedSecret.config }}
            - secretRef:
                name: {{ $key }}
            {{- end }}
            {{- end }}
          {{- end }}

          ports:
            - name: container-port
              containerPort: {{ .Values.api.container.port }}
              protocol: TCP
          
          {{- with .Values.api.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.api.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.api.startupProbe }}
          startupProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}

          resources:
            {{- toYaml .Values.api.resources | nindent 12 }}
      {{- with .Values.api.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.api.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.api.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end -}}