{{- if .Values.api.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "pearl.api.fullname" . }}
  labels: 
    {{- include "pearl.api.labels" . | nindent 4 }}
spec:
  type: {{ .Values.api.service.type }}
  ports:
    - port: {{ .Values.api.service.port }}
      targetPort: container-port
      protocol: TCP
      name: service-port
  selector: 
    {{- include "pearl.api.selectorLabels" . | nindent 4 }}
{{- end }}
