apiVersion: v2
name: meshuggah
description: A Helm chart for Meshuggah API and DB

dependencies:
  - name: postgresql
    condition: postgresql.enabled
    version: 12.1.9
    repository: https://charts.bitnami.com/bitnami

type: application
version: 0.1.0
appVersion: "1.16.0"
