apiVersion: v2
name: meshuggah
description: A Helm chart for Meshuggah API and DB

dependencies:
  - name: postgresql
    condition: postgresql.enabled
    version: 12.12.10
    repository: https://charts.bitnami.com/bitnami

type: application
version: 0.2.0
appVersion: "1.16.0"
