apiVersion: v2
name: public-enemy
description: A Helm chart for Public Enemy API, UI and DB

dependencies:
  - name: postgresql
    condition: postgresql.enabled
    version: 12.2.7
    repository: https://charts.bitnami.com/bitnami

type: application
version: 0.5.7
appVersion: "2.0.0"
