{{- if .Values.api.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "orbeon-existdb.api.fullname" . }}
  labels:
    {{- include "orbeon-existdb.api.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.api.deploymentAnnotations | nindent 4 }}
spec:
  {{- if not .Values.api.autoscaling.enabled }}
  replicas: {{ .Values.api.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "orbeon-existdb.api.selectorLabels" . | nindent 6 }}
  {{- with  .Values.deploymentStrategy }}
  strategy: 
    {{- toYaml . | nindent 4 }}
  {{- end }}
  template:
    metadata:
      annotations:
      {{- with .Values.api.podAnnotations }}
      {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "orbeon-existdb.api.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.api.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.api.podSecurityContext }} # S'il y a des values, ça écrit "securityContext:" et la suite, sinon ça ne met rien 
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.api.securityContext | nindent 12 }}
          image: "{{ .Values.api.image.repository }}:{{ .Values.api.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.api.image.pullPolicy }}
          volumeMounts:
            - name: {{ include "orbeon-existdb.api.volume.existdb" . }}
              mountPath: /db
              readOnly: false
            - name: {{ include "orbeon-existdb.api.volume.existdata" . }}
              mountPath: /exist/data
              readOnly: false
            - name: {{ include "orbeon-existdb.api.volume.existlogs" . }}
              mountPath: /exist/logs
              readOnly: false
          ports:
            - name: http
              containerPort: {{ .Values.api.container.port }}
              protocol: TCP
            - name: http2
              containerPort: {{ .Values.api.container.port2 }}
              protocol: TCP
          resources:
            {{- toYaml .Values.api.resources | nindent 12 }}
      volumes: 
        - name: {{ include "orbeon-existdb.api.volume.existdb" . }}
          ephemeral:
            volumeClaimTemplate:
              spec:
                accessModes: [ "ReadWriteOnce" ]
                resources:
                  requests:
                    storage: {{ .Values.api.storage.db.size }} 
        - name: {{ include "orbeon-existdb.api.volume.existdata" . }}
          ephemeral:
            volumeClaimTemplate:
              spec:
                accessModes: [ "ReadWriteOnce" ]
                resources:
                  requests:
                    storage: {{ .Values.api.storage.data.size }} 
        - name: {{ include "orbeon-existdb.api.volume.existlogs" . }}
          ephemeral:
            volumeClaimTemplate:
              spec:
                accessModes: [ "ReadWriteOnce" ]
                resources:
                  requests:
                    storage: {{ .Values.api.storage.logs.size }} 
      {{- with .Values.api.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.api.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.api.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end -}}