{{- if .Values.api.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "platine-access.api.fullname" . }}
  labels:
    app: {{ template "platine-access.api.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
{{- if .Values.api.env }}
{{- range $key, $value := .Values.api.env }}
  {{ $key }}: {{ $value | quote }}
{{- end -}}
{{- end -}}
{{- end -}}