{{- if .Values.enoxml.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "eno-ws.enoxml.fullname" . }}
  labels:
    {{- include "eno-ws.enoxml.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.enoxml.deploymentAnnotations | nindent 4 }}
spec:
  {{- if not .Values.enoxml.autoscaling.enabled }}
  replicas: {{ .Values.enoxml.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "eno-ws.enoxml.selectorLabels" . | nindent 6 }}
  {{- with  .Values.deploymentStrategy }}
  strategy: 
    {{- toYaml . | nindent 4 }}
  {{- end }}
  template:
    metadata:
      {{- with .Values.enoxml.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "eno-ws.enoxml.selectorLabels" . | nindent 8 }}
        {{- with .Values.enoxml.podAnnotationsLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.enoxml.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
     {{- with .Values.enoxml.podSecurityContext }} # S'il y a des values, ça écrit "securityContext:" et la suite, sinon ça ne met rien 
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.enoxml.securityContext | nindent 12 }}
          image: "{{ .Values.enoxml.image.repository }}:{{ .Values.enoxml.image.tag }}"
          imagePullPolicy: {{ .Values.enoxml.image.pullPolicy }}
          env:
            - name: FR_INSEE_ENOWS_API_SCHEME
              value: {{ include "render-value" (dict "value" .Values.enoxml.env.FR_INSEE_ENOWS_API_SCHEME "context" $) | quote }}
          # ça ne marche pas si on met le chemin direct, d'où le "range"
          {{- range .Values.enoxml.ingress.hosts}}
            - name: FR_INSEE_ENOWS_API_HOST
              value: {{ include "render-value" (dict "value" .host "context" $) | quote }}
          {{- end}}
          ports:
            - name: http
              containerPort: {{ .Values.enoxml.container.port }}
              protocol: TCP
          {{- with .Values.enoxml.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.enoxml.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.enoxml.resources | nindent 12 }}
      {{- with .Values.enoxml.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.enoxml.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.enoxml.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end -}}