{{- if .Values.enoxml.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "eno-ws.enoxml.fullname" . }}
  labels:
    {{- include "eno-ws.enoxml.labels" . | nindent 4 }}
spec:
  {{- if not .Values.enoxml.autoscaling.enabled }}
  replicas: {{ .Values.enoxml.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "eno-ws.enoxml.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.enoxml.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "eno-ws.enoxml.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.enoxml.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "eno-ws.enoxml.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.enoxml.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.enoxml.securityContext | nindent 12 }}
          image: "{{ .Values.enoxml.image.repository }}:{{ .Values.enoxml.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.enoxml.image.pullPolicy }}
          env:
            - name: FR_INSEE_ENOWS_API_SCHEME
              value: https
          # ça ne marche pas si on met le chemin direct, d'où le "range"
          {{- range .Values.enoxml.ingress.hosts}}
            - name: FR_INSEE_ENOWS_API_HOST
              value: {{ .host }}
          {{- end}}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          resources:
            {{- toYaml .Values.enoxml.resources | nindent 12 }}
      {{- with .Values.enoxml.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.enoxml.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.enoxml.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end -}}