{{if and .Values.enoxml.enabled .Values.enoxml.serviceAccount.create}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "eno-ws.enoxml.serviceAccountName" . }}
  labels:
    {{- include "eno-ws.enoxml.labels" . | nindent 4 }}
  {{- with .Values.enoxml.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
