{{- if .Values.api.enabled }}
{{- $basePath := . }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "ui-api-db.api.fullname" . }}
  labels:
    app: {{ template "ui-api-db.api.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
{{- if .Values.api.env }}
{{- range $key, $value := .Values.api.env }}
  {{ $key }}: {{ include "render-value" ( dict "value" $value "context" $basePath ) | quote }}
{{- end -}}
{{- end -}}
{{- end -}}