{{- if .Values.api.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ui-api-db.api.fullname" . }}
  labels:
    {{- include "ui-api-db.api.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.api.deploymentAnnotations | nindent 4 }}
spec:
  {{- if not .Values.api.autoscaling.enabled }}
  replicas: {{ .Values.api.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "ui-api-db.api.selectorLabels" . | nindent 6 }}
  {{- with  .Values.deploymentStrategy }}
  strategy: 
    {{- toYaml . | nindent 4 }}
  {{- end }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/api/configmap.yaml") . | sha256sum }}
      {{- with .Values.api.podAnnotations }}
      {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "ui-api-db.api.selectorLabels" . | nindent 8 }}
        {{- with .Values.api.podAnnotationsLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.api.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.api.podSecurityContext }} # S'il y a des values, ça écrit "securityContext:" et la suite, sinon ça ne met rien 
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.postgresql.enabled }}
      initContainers:
        - name: check-db-ready
          image: postgres:11.6
          command: ['sh', '-c', 
            until pg_isready -h {{ include "ui-api-db.postgresql.fullname" . }} -p {{ .Values.postgresql.auth.port}}; 
            do echo waiting for database; sleep 2; done;]
          resources:
            {{- toYaml .Values.api.resources | nindent 12 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.api.securityContext | nindent 12 }}
          image: "{{ .Values.api.image.repository }}:{{ .Values.api.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.api.image.pullPolicy }}
          env:
          {{- if .Values.postgresql.enabled }}
            - name: SPRING_DATASOURCE_URL
              value:  {{ printf "jdbc:postgresql://%s:%.0f/%s" (include "ui-api-db.postgresql.fullname" .) .Values.postgresql.auth.port .Values.postgresql.auth.database | quote }}
            - name: SPRING_DATASOURCE_USERNAME
              value: {{ .Values.postgresql.auth.username | quote}}
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "ui-api-db.postgresql.fullname" .}}
                  key: password
          {{- end }}
          {{- if .Values.vaultStaticSecret.enabled }}
            {{- range $key, $value := .Values.vaultStaticSecret.config }}
            - name:  {{ $value.envName }}
              valueFrom:
                secretKeyRef: 
                  name: {{ $value.secretName }}
                  key:  {{ $value.keyUsed }}
            {{- end }}
          {{- end }}
          {{- if and .Values.api.env .Values.api.enabled }}
          envFrom:
            - configMapRef:
                name: {{ template "ui-api-db.api.fullname" . }}
          {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.api.container.port }}
              protocol: TCP
          {{- with .Values.api.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.api.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.api.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.api.resources | nindent 12 }}
      {{- with .Values.api.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.api.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.api.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end -}}
