{{- if .Values.vaultStaticSecret.enabled -}}
{{- range $key, $value := .Values.vaultStaticSecret.config }}
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: {{ $key }}
spec:
  rolloutRestartTargets:
    - kind: Deployment 
      name: {{ include "ui-api-db.api.fullname" $ }}

  type: kv-v2

  # mount path
  mount:  {{ $value.mount }}

  # path of the secret
  path: {{ $value.path }}

  # dest k8s secret
  destination:
    name: {{ $value.secretName }}
    create: true

  # static secret refresh interval
  refreshAfter: {{ $value.refreshAfter }}

  # Name of the CRD to authenticate to Vault
  vaultAuthRef: {{ $value.vaultAuthRef }}
{{- end }}
{{- end -}}