ui:
  enabled: false
  nameOverride: ""
  fullnameOverride: ""
  image:
    repository: inseefr/stromae
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: ""

  service:
    port: 80
    type: ClusterIP

  container:
    port: 8080

  replicaCount: 1
  # if autoscaling is enabled, replicaCount is not read
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 10
    targetCPUUtilizationPercentage: 80
    targetMemoryUtilizationPercentage: 80
  env:
    STROMAE_DB_USERNAME: admin
    STROMAE_DB_PASSWORD: ""
    STROMAE_DB_URL: "http://admin:@host-of-db.example.org"
    ORBEON_EXIST: "exist"
    ORBEON_EXIST_COLLECTION: "exist/rest/db/orbeon/fr"
    STROMAE_HOST: ""
    URL_LOGOUT: ""

  nodeSelector: {}

  volumes: {}

  volumeMounts: {}

  tolerations: []

  affinity: {}

  networkPolicy:
    enabled: false

  podSecurityContext: {}
  # fsGroup: 2000

  securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

  ingress:
    enabled: false
    className: ""
    annotations:
      {}
      # kubernetes.io/ingress.class: nginx
      # kubernetes.io/tls-acme: "true"
    hosts:
      - host: chart-example.local
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls: []
    #  - secretName: chart-example-tls
    #    hosts:
    #      - chart-example.local

api:
  enabled: false
  nameOverride: ""
  fullnameOverride: ""
  storage:
    db:
      size: 1Gi
    data:
      size: 1Gi
    logs:
      size: 10Mi

  image:
    repository: inseefr/stromae-db
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: ""

  service:
    type: ClusterIP
    port: 80

  container:
    port: 8080
    port2: 8443

  replicaCount: 1
  # if autoscaling is enabled, replicaCount is not read
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 10
    # # targetCPUUtilizationPercentage: 80
    # targetMemoryUtilizationPercentage: 80

  nodeSelector: {}

  tolerations: []

  affinity: {}

  env: {}

  podSecurityContext: {}
  # fsGroup: 2000

  securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

  networkPolicy:
    enabled: false

  ingress:
    enabled: false
    className: ""
    annotations:
      {}
      # kubernetes.io/ingress.class: nginx
      # kubernetes.io/tls-acme: "true"
    hosts:
      - host: chart-example.local
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls: []
    #  - secretName: chart-example-tls
    #    hosts:
    #      - chart-example.local
