{{- if .Values.ui.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ui-api-db.ui.fullname" . }}
  labels: 
    {{- include "ui-api-db.ui.labels" . | nindent 4 }}
spec:
  type: {{ .Values.ui.service.type }}
  ports:
    - port: {{ .Values.ui.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector: 
    {{- include "ui-api-db.ui.selectorLabels" . | nindent 4 }}
{{- end }}
